---
  ##############################
  #    Configuration nginx     #
  #############################

- name: Installation nginx
  apt:
    name: nginx
    state: latest
  notify: restart nginx

#- name: Suppression de default.conf
#  file: path=/etc/nginx/sites-enabled/default state=absent
#  notify: reload nginx

- name: DELETE DEFAULT nginx.conf
  file: path=/etc/nginx/nginx.conf state=absent

- name: SITE CONFIGURATION
  include_tasks: site.yml
