---
- hosts: web
  remote_user: osr
  vars:
    user: amadou
    mysql_db:
      - name: osr_db_db
    mysql_users:
      - name: osr
        pass: osr_db@osr.com
        db: osr_db_db
    domains:
      - domain: opensuccessroom
        php: yes
    node_v: 8
    os_name: xenial
    mysql_root_passwd: MaAmAbHoAsDi

  roles:
    - utils
    - user
    - php
  #  - mysql
    - nginx
    - node
    - ssh
    - security
...
