---
- name: Disallow root SSH access
  become: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart ssh

- name: "Seulmant l'utilisateur {{ user }} pourra se connecter"
  become: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^AllowUsers" line="AllowUsers {{ user }}" state=present
  notify: restart ssh

- name: Interdiction de se connecter avec mot de passe
  become: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh

- name: changement du port par defaut de SSH
  become: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^Port 22" line="Port {{ ssh_port }}" state=present
  notify: restart ssh
