---
- name: MySQL Install
  apt:
    name:
      #- mysql-server
      - python-mysqldb
    state: present
#- name: Install MySQL-python
#  pip: executable=pip3 name=MySQL-python
#- name: MySQL | Set root password
#  mysql_user:
#    name: root
#    password: "{{ mysql_root_password }}"
#    check_implicit_admin: yes
#    login_user: root
#    login_password: ""
#    state: present
- name: MySQL | Remove anonyme user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: ""
    state: absent
- name: MySQL | remove database test
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent
- name: MySQL | Create all database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: "{{ mysql_db }}"
    state: present
- name: "MySQL | create User {{ mysql_user }}"
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_db }}.*:ALL,GRANT"
    host: localhost
    state: present
