---
- name: Installation de mysql
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

#- name: mettre à jour le mot de passe root de tous les comptes
#  become: yes
#  mysql_user: name=root host_all=yes password={{ mysql_root_passwd }}
#  notify: restart mysql

#- name: s'assurer qu'il n'ya pas d'utilisateur anonyme dans la base donnée
#  become: yes
#  mysql_user: name='' host=localhost state=absent
#  notify: restart mysql

#- name: supprimer la base de donnée test
#  become: yes
#  mysql_db: name=test state=absent
#  notify: restart mysql

- name: Creation des bases de données neccessaire
  become: yes
  mysql_db: name={{ item.name }} state=present
  with_items:
    - "{{mysql_db}}"
  notify: restart mysql

- name: création des utilisateurs des bases de données
  become: yes
  mysql_user:
    name={{ item.name }}
    password={{ item.pass|default("osr_db@osr.com") }}
    priv="{{ item.db }}.*:ALL,GRANT"
    state=present
    host="%"
  with_items:
    - "{{ mysql_users }}"
  notify: restart mysql
  when: mysql_users|lower() != 'none'
