---
    ##################################################
    #    les outils neccessaires pour le serveur     #
    ##################################################

- name: installation des outils neccessaires des serveurs
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - git
    - curl
    - vim
    - wget
    - make
    - unzip
    - tar
    - zsh
    - htop
