---
- name: Ajout de la clef
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Ajout de node au repository
  apt_repository:
    repo="deb https://deb.nodesource.com/node_{{ node_v }}.x {{ os_name }} main"
    state: present
    update_cache: yes

- name: install nodejs package
  apt:
    pkg: nodejs
    state: present
