---
- name: Installation des modules php
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - "{{php_packages}}"

- name: Suppression de quelques fonctions dangereuses de php
  become: yes
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='disable_functions[\s]?=' line='disable_functions = exec,passthru,shell_exec,proc_open,popen'

- name: Modification du POST MAX SIZE de php
  become: yes
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='post_max_size[\s]?=' line='post_max_size = {{ php_post_max_size }}'

- name: Modification de UPLOAD MAX FILESIZE de php
  become: yes
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='upload_max_filesize[\s]?=' line='upload_max_filesize = {{ php_upload_max_filesize }}'

- name: Modification de la limit de memoire en php
  become: yes
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='memory_limit[\s]?=' line='memory_limit = {{ php_memory_limit }}'

- name: Modification du time zone de php
  become: yes
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='date.timezone[\s]?=' line='date.timezone = {{ php_timezone }}'
  notify: restart php-fpm
